### ISSUE TITLE
Crash for a large number of simultaneous ServiceX requests

### ISSUE THREAD

**Issue by kyungeonchoi** [ssl-hep/ServiceX_frontend#164]
### Story

[`servicex-for-trexfitter`](https://github.com/kyungeonchoi/ServiceXforTRExFitter) can easily create more than 100 simultaneous ServiceX requests. It runs just okay for a relatively small number of SerivceX requests, but it starts to crash more than about 100 ServiceX requests.

### Error messages

The error message is not always same. The most common one is below:
<details>
  <summary markdown="span"> aiohttp.client_exceptions.ServerDisconnectedError </summary>

```
>>> sx_trex.get_ntuples(timer=True)
Retrieving data from ServiceX Uproot backend..
user.kchoi:user.kchoi.WZana_WZ:   0%|                                                                    | 0/6 [00:00Traceback (most recent call last):                                                                        | 0/6 [00:00]
  File "<stdin>", line 1, in <module> 0%|                                                               | 0/12 [00:00]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex_for_trexfitter/servicex_for_trexfitter.py", line 43, in get_ntupleschoi.WZana_WZ:   0%|                                                                    | 0/6 [00:00]
    output_parquet_list = sx.get_servicex_data()                                                         | 0/6 [00:00]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex_for_trexfitter/communicate_servicex.py", line 48, in get_servicex_data  0%|                                                                                | 0/6 [00:00]
    data = newloop.run_until_complete(_get_my_data(list_query))                                          | 0/3 [00:00]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/nest_asyncio.py", line 70, in run_until_complete0/3 [00:00]
    return f.result().WZana_WZ:   0%|                                                                    | 0/6 [01:56]
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/futures.py", line 178, in result                    | 2/6 [01:56]
    raise self._exceptionna_WZ:   0%|                                                                    | 0/6 [01:55]
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/tasks.py", line 251, in __step                      | 2/6 [01:55]
    result = coro.throw(exc)WZ:   0%|                                                                    | 0/6 [00:00]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex_for_trexfitter/communicate_servicex.py", line 42, in _get_my_data.kchoi.WZana_WZ:   0%|                                                                    | 0/6 [00:13]
    return await asyncio.gather(*list_query)                                                             | 1/6 [00:13]
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup                    | 0/6 [01:51]
    future.result()  33%|██████████████████████████▋                                                     | 2/6 [01:51]
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/tasks.py", line 251, in __step                      | 0/6 [01:50]
    result = coro.throw(exc)███████████████████████▋                                                     | 2/6 [01:50]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex_utils.py", line 49, in cached_version_of_fn      Downloaded:  33%|██████████████████████████▋                                                     | 2/6 [01:49]
    result = await fn(*args, **kwargs)                                                                   | 0/6 [01:48]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 259, in get_data_parquet_async]
    return await self._file_return(selection_query, 'parquet')                                           | 0/6 [01:47]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 373, in _file_return2/6 [01:47]
    return await self._data_return(selection_query, convert_to_file, data_format)                        | 0/6 [01:46]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 455, in _data_return2/6 [01:46]
    async for f in self._stream_return(selection_query, converter, data_format)                          | 0/6 [01:45]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 453, in <dictcomp>| 2/6 [01:45]
    all_data = {kchoi.WZana_WZ:   0%|                                                                    | 0/6 [00:05]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 491, in _stream_return6 [00:05]
    async for r in as_data:_WZ:   0%|                                                                    | 0/6 [00:04]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 487, in <genexpr> | 1/6 [00:04]
    as_data = (StreamInfoData(f.file, await asyncio.ensure_future(converter(f.path)))                    | 0/6 [00:03]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 524, in _stream_local_files:03]
    async for name, a_path in as_files:                                                                  | 0/6 [00:00]
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 521, in <genexpr> | 0/6 [00:00]
    (f async for f in.
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 574, in _get_files
    async for r in stream_local_files:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 685, in _get_files_from_servicex
    async for info in stream_downloaded:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 654, in _download_a_file
    async for f in stream:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex.py", line 732, in _get_minio_bucket_files_from_servicex
    async for info in stream_new_object:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/minio_adaptor.py", line 173, in find_new_bucket_files
    async for _ in update:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/utils.py", line 194, in stream_unique_updates_only
    async for p in stream:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex_adaptor.py", line 234, in trap_servicex_failures
    async for p in stream:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/utils.py", line 182, in stream_status_updates
    async for p in stream:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex_adaptor.py", line 219, in transform_status_stream
    next_processed = await sa.get_transform_status(client, request_id)
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/servicex/servicex_adaptor.py", line 173, in get_transform_status
    headers=headers) as response:
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Users/kchoi/anaconda3/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
    future.result()
  File "/Users/kchoi/anaconda3/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
aiohttp.client_exceptions.ServerDisconnectedError
```

</details>

Other type is:
<details>
  <summary markdown="span"> servicex.utils.ServiceXException: (ServiceXException(...), 'ServiceX rejected the transformation request: (500){"message": "Something went wrong"}\n') </summary>

```
>>> sx_trex.get_ntuples(timer=True)
Retrieving data from ServiceX Uproot backend..
user.kchoi:user.kchoi.Traceback (most recent call last):██████████████████████████████                                                 | 3/6 [00:00]
  File "<stdin>", line 1, in <module>                                                                                                  | 0/6 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex_for_trexfitter/servicex_for_trexfitter.py", line 43, in get_ntuples00]
    output_parquet_list = sx.get_servicex_data()                                                                                       | 0/6 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex_for_trexfitter/communicate_servicex.py", line 48, in get_servicex_data
    data = newloop.run_until_complete(_get_my_data(list_query))                                                                        | 0/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/nest_asyncio.py", line 98, in run_until_complete                  | 1/3 [00:00]
    return f.result() 0%|                                                                                                              | 0/3 [00:00]
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 182, in _step████████████████████                                                 | 3/6 [00:00]
    result = coro.throw(exc)                                                                                                           | 0/6 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex_for_trexfitter/communicate_servicex.py", line 42, in _get_my_data0:00]
    return await asyncio.gather(*list_query)                                                                                           | 0/3 [00:00]
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 250, in _wakeup                                                                   | 0/3 [00:00]
    future.result()oi.WZana_WZ:  50%|█████████████████████████████████████████████████                                                 | 3/6 [00:00]
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 180, in _step                                                                     | 0/6 [00:00]
    result = coro.send(None)ZZ:  33%|████████████████████████████████▋                                                                 | 1/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex_utils.py", line 49, in cached_version_of_fn     | 0/3 [00:00]
    result = await fn(*args, **kwargs)███████████████████████████████▋                                                                 | 1/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 259, in get_data_parquet_async        | 0/3 [00:00]
    return await self._file_return(selection_query, 'parquet')                                                                         | 0/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 373, in _file_return                  | 1/3 [00:00]
    return await self._data_return(selection_query, convert_to_file, data_format)                                                      | 0/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 455, in _data_return                  | 1/3 [00:00]
    async for f in self._stream_return(selection_query, converter, data_format)                                                       | 0/12 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 453, in <dictcomp>                    | 0/3 [00:00]
    all_data = {kchoi.WZana_ZZ:  33%|████████████████████████████████▋                                                                 | 1/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 491, in _stream_return                | 0/3 [00:00]
    async for r in as_data:_ZZ:  33%|████████████████████████████████▋                                                                 | 1/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 487, in <genexpr>                    | 0/19 [00:00]
    as_data = (StreamInfoData(f.file, await asyncio.ensure_future(converter(f.path)))                                                  | 0/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 524, in _stream_local_files           | 0/3 [00:00]
    async for name, a_path in as_files:███████████████████████████████████████████████████████████████▎                                | 2/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 521, in <genexpr>                     | 0/3 [00:00]
    (f async for f in.WZana_WZ:  83%|█████████████████████████████████████████████████████████████████████████████████▋                | 5/6 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 559, in _get_files                    | 0/6 [00:00]
    request_id = await self._get_request_id(client, query)███████████▋                                                                 | 1/3 [00:00]
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex.py", line 605, in _get_request_id               | 0/3 [00:00]
    request_info = await self._servicex_adaptor.submit_query(client, query)
  File "/afs/cern.ch/user/k/kchoi/.local/lib/python3.6/site-packages/servicex/servicex_adaptor.py", line 66, in submit_query
    raise ServiceXException('ServiceX rejected the transformation request: '
servicex.utils.ServiceXException: (ServiceXException(...), 'ServiceX rejected the transformation request: (500){"message": "Something went wrong"}\n')
```

</details>

### Observation

- `servicex-for-trexfitter` prepares ServiceX requests and then starts to make requests. It crashes while updating progress bars. I think the first error is while it tries to get the status of transformation and the second is while it is making transformation requests.
- Regardless of crash, transformation jobs are always finished without any problem as they can be checked from the dashboard.

### Reproduce

You may reproduce the error using the following file with `servicex-for-trexfitter==0.7.1` (latest version).
```
from servicex_for_trexfitter import ServiceXTRExFitter
sx_trex = ServiceXTRExFitter('config/195requests.config')
sx_trex.get_ntuples()
```
The input file can be found [here](https://github.com/kyungeonchoi/ServiceXforTRExFitter/blob/development/config/195requests.config).
I tested at lxplus, UT machine, and my laptop (Mac).

### Possible source

Since it happens only when there are too many coroutines running at the same time, it should be something to do with a handling of the maximum simultaneous connections between backend and frontend. Maybe we need to limit the number of active connections from the frontend library or significantly increase maximum connections to the backend.

### Temporary solution for `servicex-for-trexfitter`

I'm working on a patch to limit maximum ServiceX requests from the `servicex-for-trexfitter`. However, we need to have a better solution as transformers are running without any problem.

**Comment by gordonwatts** [comment]
I think the fact that the transformations always complete - and there is never a crash on the services backend, that the error must be in the frontend.

Also, you didn't mention it above, @kyungeonchoi , but is it still the case that different sized memory machines show different behavior? That is, the larger the machine, the more number of connections it can handle?

**Comment by kyungeonchoi** [comment]
@gordonwatts - I guess this can be handled by the frontend, but maybe it's something to do with some settings of the backend.

Regarding the dependence on the memory size of the machine, it seems like it's more to do with the version of `aiohttp` package. The behavior is similar after updating and matching the version for all machines. Moreover, the memory usage is less than 500 MB, so should be okay.

**Comment by ponyisi** [comment]
A few ideas from me about this -
* it would almost certainly improve throughput if status request updates could be batched - i.e. frontend makes 1 request for updates on 100 transformations rather than 100 requests. I don't know how well this plays with the async design, and it would require a new API on the backend side, but it's going to be more efficient.
* the frontend should be more robust against transient connection errors to the backend.
* the scalability of the REST API service should be checked.

**Comment by gordonwatts** [comment]
@kyungeonchoi - wow - the version of `aiohttp` - that is great; great find!!! - let me make sure, however. The older version was having more crashes than the newer version? Or is only the newer version crashing?

The batching idea sounds like a  good one. It would require some major changes to how that part worked in the backend of the frontend, however, those changes would not be visible to the user - so that is very good!

**Comment by gordonwatts** [comment]
Another question, @kyungeonchoi  - how accurate is the 100 connections? I ask because: https://github.com/aio-libs/aiohttp/issues/4923 ;-)

**Comment by kyungeonchoi** [comment]
@gordonwatts - sorry for the slow response! on vacation this week :) 

According to my limited number of tests, I would say it's more stable (or less error prone) with the later version of `aiohttp`. 

It's an interesting issue since its behavior is the same as what I have. I don't think there is a hard threshold of 100 connections but that's in the ballpark.

**Comment by kyungeonchoi** [comment]
I've updated `servicex-for-trexfitter==0.8.1` to limit maximum concurrent ServiceX requests to 50 as a temporary solution. It works just fine for various edge tests as expected.

@gordonwatts - one test I'd like to report is that the backend seems stable when there are 150 active ServiceX requests (50 requests each and simultaneously from three different machines at lxplus, UT and my laptop). I think this tells us that the error should be handled by the frontend or a client package like `servicex-for-trexfitter`.

**Comment by gordonwatts** [comment]
Awesome - thanks for checking. I think this really says this is a bug in the frontend, and the frontend needs to be fixed. I'll get to this shortly. I've got other bigger failures I need to take care of first, however.

**Comment by ponyisi** [comment]
Is this a test we can repeat with 3.0?

**Comment by gordonwatts** [comment]
Lets close this. I've run with 3.0 and not see crashes. And when we update with new datasets, then we can continue to test, and we'll have a new bug report if we see new crashs.
