### ISSUE TITLE
Protect against filenames that are too long

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#165]
Crash when the `minio` bucket is translated into a filename directly - and exceeds the maximum filename length on an `ext4` volume (255 characters). Stack dump:

```
Traceback (most recent call last):
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/servicex.py", line 592, in _get_files
    async for r in stream_local_files:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/servicex.py", line 704, in _get_files_from_servicex
    async for info in stream_downloaded:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/servicex.py", line 673, in _download_a_file
    async for f in stream:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/servicex.py", line 751, in _get_minio_bucket_files_from_servicex
    async for info in stream_new_object:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/minio_adaptor.py", line 176, in find_new_bucket_files
    async for _ in update:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/utils.py", line 206, in stream_unique_updates_only
    async for p in stream:
  File "/home/burt/.local/lib/python3.6/site-packages/servicex/servicex_adaptor.py", line 237, in trap_servicex_failures
    raise ServiceXFailedFileTransform(f'ServiceX failed to transform {did_fail} '
servicex.utils.ServiceXFailedFileTransform: (ServiceXFailedFileTransform(...), 'ServiceX failed to transform 1 files - data incomplete (remaining: 3, processed: 0).')
```

**Comment by gordonwatts** [comment]
This was reported by Burt Holtzman.

As he suggested, looks like we might need to implement some sort of local filename hashing in order to protect against this (or similar).

**Comment by gordonwatts** [comment]
This has been turned into a bug over on the ServiceX project as it actually is a bug in the transformers that is occurring. The services frontend actually has some protection already!

See this [bug](https://github.com/ssl-hep/ServiceX/issues/303) for more info.
