### ISSUE TITLE
Properly detect a DID not found

### ISSUE THREAD

**Issue by gordonwatts** [ssl-hep/ServiceX_frontend#30]
The error due to a bogus DID isn't properly bubbled up to the user. Not yet obvious, either, how servicex responds

**Comment by gordonwatts** [comment]
From slack conversation... The status message will return:
```
{
    "files-processed": 0,
    "files-remaining": null,
    "files-skipped": 0,
    "request-id": "8cd40723-2cb9-4483-b71c-219e870ee2ba",
    "stats": null,
    "status": "Fatal"
}
```

At that point do a get on the request id for a transform and you'll get back something like this:

```
{
    "request_id": "3a52b35c-8cc7-4740-9c14-b6556d350471",
    "did": "mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.e3601_s2576_s2132_r6630_r6264_p2363_tid05630052_00XXXX",
    "columns": null,
    "selection": "(call ResultTTree (call Select (call Select (call EventDataset (list 'localds:bogus')) (lambda (list e) (list (call (attr e 'Electrons') 'Electrons') (call (attr e 'Muons') 'Muons')))) (lambda (list e) (list (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'e')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'pt')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'phi')))) (call (attr (subscript e 0) 'Select') (lambda (list ele) (call (attr ele 'eta')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'e')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'pt')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'phi')))) (call (attr (subscript e 1) 'Select') (lambda (list mu) (call (attr mu 'eta'))))))) (list 'e_E' 'e_pt' 'e_phi' 'e_eta' 'mu_E' 'mu_pt' 'mu_phi' 'mu_eta') 'forkme' 'dude.root')",
    "tree-name": null,
    "image": "sslhep/servicex_func_adl_xaod_transformer:develop",
    "chunk-size": 7000,
    "workers": 1,
    "result-destination": "object-store",
    "result-format": "root-file",
    "kafka-broker": null,
    "workflow-name": "selection_codegen",
    "generated-code-cm": "3a52b35c-8cc7-4740-9c14-b6556d350471-generated-source",
    "status": "Fatal",
    "failure-info": "DID Not found mc15_13TeV:mc15_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.merge.DAOD_STDM3.e3601_s2576_s2132_r6630_r6264_p2363_tid05630052_00XXXX",
    "minio-endpoint": "servicex--minio:9000",
    "minio-access-key": "miniouser",
    "minio-secret-key": "leftfoot1"
}
```

Which can then be reported to the user.

https://iris-hep.slack.com/archives/GLJSS8FPE/p1595868323314100

**Comment by gordonwatts** [comment]
Other possible values of status: "Running", "Complete".

**Comment by gordonwatts** [comment]
Now look at it:
```
(.venv) PS C:\Users\gordo\Documents\Code\IRIS-HEP\ServiceX_frontend> python .\scripts\run_test.py
Traceback (most recent call last):
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 252, in _get_files
    async for r in stream_local_files:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 364, in _get_files_from_servicex
    async for info in stream_downloaded:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 330, in _download_a_file
    async for f in stream:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\minio_adaptor.py", line 189, in find_new_bucket_files
    async for _ in update:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\utils.py", line 189, in stream_unique_updates_only
    async for p in stream:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex_adaptor.py", line 256, in trap_servicex_failures
    async for p in stream:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\utils.py", line 177, in stream_status_updates
    async for p in stream:
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex_adaptor.py", line 241, in transform_status_stream
    next_processed = await sa.get_transform_status(client, request_id)
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex_adaptor.py", line 205, in get_transform_status
    raise ServiceXFatalTransformException(f'Transform status for {request_id}'
servicex.utils.ServiceXFatalTransformException: (ServiceXFatalTransformException(...), 'Transform status for a708e3a3-e93c-4ff1-b515-bd890fb66ccd is marked "Fatal".')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\scripts\run_test.py", line 29, in <module>
    run_query(servicex_adaptor)
  File ".\scripts\run_test.py", line 18, in run_query
    r = ds.get_data_rootfiles("(call ResultTTree (call Select (call SelectMany (call EventDataset (list 'localds:bogus')) (lambda (list e) (call (attr e 'Jets') 'AntiKt4EMTopoJets'))) (lambda (list j) (/ (call (attr j 'pt')) 1000.0))) (list 'JetPt') 'analysis' 'junk.root')")  # NOQA
  File "C:\Users\gordo\Documents\Code\IRIS-HEP\ServiceX_frontend\.venv\lib\site-packages\make_it_sync\func_wrapper.py", line 57, in wrapped_call
    return _sync_version_of_function(v, *(args[1:]), **kwargs)
  File "C:\Users\gordo\Documents\Code\IRIS-HEP\ServiceX_frontend\.venv\lib\site-packages\make_it_sync\func_wrapper.py", line 14, in _sync_version_of_function
    return loop.run_until_complete(r)
  File "C:\Users\gordo\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex_utils.py", line 49, in cached_version_of_fn
    result = await fn(*args, **kwargs)
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 118, in get_data_rootfiles_async
    return await self._file_return(selection_query, 'root-file')
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 161, in _file_return
    return await self._data_return(selection_query, convert_to_file, data_format)
  File "C:\Users\gordo\Documents\Code\IRIS-HEP\ServiceX_frontend\.venv\lib\site-packages\backoff\_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 200, in _data_return
    all_data = {f[0]: await f[1] async for f in as_data}
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 200, in <dictcomp>
    all_data = {f[0]: await f[1] async for f in as_data}
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 195, in <genexpr>
    as_data = ((f[0], asyncio.ensure_future(converter(await f[1])))
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 191, in <genexpr>
    (f async for f in
  File "c:\users\gordo\documents\code\iris-hep\servicex_frontend\servicex\servicex.py", line 267, in _get_files
    f'ServiceX Fatal Error: {transform_status["failure-info"]}') from e
servicex.utils.ServiceXFatalTransformException: (ServiceXFatalTransformException(...), 'ServiceX Fatal Error: DID Not found mc16_13TeV:mc16_13TeV.361106.PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zee.deriv.DAOD_STDM3.e3601_e5984_s3126_r10201_r10210_p3975_tid20425969_00llll')
```
